# Since your Rust package lives in a subfolder, I will make this a workspace.
#
# This may not work properly with PyO3, so you might need to fix that.
[workspace]
members = ["dynamixplore/rust_core"]

[workspace.package]
authors = []
name = "dynamixplore"
version = "0.1.0"
edition = "2024"
