# This workflow runs tests on every push and pull request to ensure code correctness.

name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test on ${{ matrix.os }} / Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      # Run tests on all major operating systems and Python versions
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      # 1. Check out the repository code
      - name: Check out repository
        uses: actions/checkout@v4

      # 2. Set up the specified Python version
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      # 3. Set up the Rust toolchain
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      # 4. Install Python dependencies, including testing tools
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-benchmark numpy plotly scipy

      # 5. Install the dynamixplore package itself in editable mode
      # This compiles the Rust core and makes the Python package available.
      - name: Install dynamixplore
        uses: PyO3/maturin-action@v1
        with:
          command: develop
          args: --release

      # 6. Run the test suite
      - name: Run tests with pytest
        run: pytest
