name: Build and Deploy Docs

# Run this workflow every time a push is made to the `main` branch
on:
  push:
    branches:
      - main

# Allow this job to create a GitHub Pages deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out your repository's code
      - name: Checkout
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Or your desired version

      # Step 3: Install your project's dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt # Assumes you have a requirements file

      # Step 4: Build the Sphinx documentation
      - name: Build Sphinx docs
        run: |
          make -C docs html

      # Step 5: Upload the generated website as an artifact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/build/html

      # Step 6: Deploy the artifact to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4