# This workflow builds the Sphinx documentation and deploys it to GitHub Pages.

name: Deploy Documentation

on:
  # Run only when pushing to the main branch
  push:
    branches:
      - main

# Grant permissions for the workflow to deploy to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      # 1. Check out the repository code
      - name: Check out repository
        uses: actions/checkout@v4

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 3. Install documentation dependencies from a requirements file
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt

      # 4. Install your own package so Sphinx can import it
      - name: Install dynamixplore
        uses: PyO3/maturin-action@v1
        with:
          command: develop

      # 5. Build the Sphinx documentation
      # This command tells Sphinx to build the HTML from the 'docs/source' directory
      # and put the output in the 'docs/_build/html' directory.
      - name: Build Sphinx documentation
        run: sphinx-build -b html docs/source docs/_build/html

      # 6. Upload the built HTML as a GitHub Pages artifact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "docs/_build/html"

  # This job takes the artifact from the build job and deploys it
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-docs # This job runs only after the build-docs job is successful
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
