# .github/workflows/release-please.yml

name: Release Please

on:
  push:
    branches:
      - main

# This is the most important change: Granting write permissions
permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      # This uses the new, correct path for the action
      - uses: googleapis/release-please-action@v4
        with:
          # We now point to a configuration file instead of putting
          # all the options here directly.
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
