# .github/workflows/release-please.yml

name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          # This is the key change:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}

          # The rest remains the same
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
